# Generated by Django 3.2.1 on 2021-09-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default='', null=''),
            preserve_default=False,
        ),
    ]
